### ISSUE TITLE
JavaScript interface

### ISSUE THREAD

**Issue by klokan** [klokantech/osmnames-sphinxsearch#11]
With autocomplete and a map showing bounding box.

**Comment by klokan** [comment]
@petrsloup - I think the best would be to reuse in the interface the autocomplete component we will use everywhere else - instead of developing a code specific just for the osmnames website.

What if the user interface looks and behaves like:
https://www.mapbox.com/bites/00121/?mapid=tatiana.e6d7f624&marker-color=e95591&demo=1

What do you think?

**Comment by petrsloup** [comment]
@klokan Okay.. I though this was also supposed to be usable for debugging of the indexing and searching demo -- that's why more results are shown including the complete item data in the "details" box.

So (as discussed yesterday):
- I will create `kt.OsmNames` class for autocomplete in our standard javascript library (https://github.com/klokantech/javascript/tree/master/src) based on the existing `kt.Nominatim` autocomplete. We can later improve the display name formatting (type vs class, etc.) and fine-tune the user interaction there so it can be directly used in all our products.
- Separate component handling the map (automatically deciding whether to use vector (mapbox-gl-js + ol3) or raster (ol3 only) tiles + correctly handling HiDPI devices)
- It will be possible to optionally pass the map instance to the `kt.OsmNames` constructor. If passed, the map's view extent will be automatically fitted to the search result after autocompleting.

**Comment by petrsloup** [comment]
I think this can be closed now..
