### ISSUE TITLE
Ranking boosting improving exact hit

### ISSUE THREAD

**Issue by klokan** [klokantech/osmnames-sphinxsearch#13]
Problem: search for "Bern" gives you "Bayern" on first place.
Search for "Baar" should first (or only?) return Baar records (one in Switzerland, then in Germany).

**Comment by klokan** [comment]
Another test phrases: "Brno" or "Halkova, Brno".

**Comment by klokan** [comment]
Status @MartinMikita?

**Comment by MartinMikita** [comment]
1. I changed ranker itself to this formula `sum((10*lcs+5*exact_order+5*exact_hit+5*wlccs)*user_weight)*1000+bm25` (normal RANK_SPH04 is `sum((4*lcs+2*(min_hit_pos==1)+exact_hit)*user_weight)*1000+bm25`)
2. I have added function for processing with mysql protocl (SphinxQL language) instead of Sphinx API which is old and very limited.
3. Using SphinxQL (with combination of SQL) we have weight calculated as `WEIGHT()*importance+IF(name=<query>,1000000,0)`, which boost query == name, case insensitive.
4. Search is done in loop for base index (Without any modifications), than with soundex modifications (if no results found).

**Comment by MartinMikita** [comment]
http://osmnames.klokantech.com/?q=bern&format=html
http://osmnames.klokantech.com/?q=halkova%2C+brno&format=html
http://osmnames.klokantech.com/?q=unterageri+zug&format=html
http://osmnames.klokantech.com/?q=grand+canyon&format=html
http://osmnames.klokantech.com/?q=bayern&format=html
http://osmnames.klokantech.com/?q=brno&format=html
