### ISSUE TITLE
Autocomplete isn't bringing up results for postcodes when filtered by country

### ISSUE THREAD

**Issue by nicholasgriffintn** [klokantech/osmnames-sphinxsearch#56]
I want to be able to filter autocomplete results to come only from the UK while being able to run a postcode search, I have managed to filter it to only UK results, however, now postcode search doesn't work (it does work when the results aren't filtered).

Here's my code:

Also here's a screen of the implementation and the search:

**Comment by MartinMikita** [comment]
Thanks for your feedback.

The problem is now in the combination of data and the search engine together.

This search engine is now using OSMNames data and GB (United Kingdom) postcodes, which was implemented in #41 as a paid customization by the customer.

The pre-processed data of GB postcodes do not contain the field `country_code` (it wasn't required by the customer and it wasn't necessary to identify them, because it is used only for GB country).

As the results, you are not able to filter data over `country_code` for postcodes now.

We are probably going to fix this issue in our time in the following months.

Or you can purchase a [commercial support](https://www.klokantech.com/support/) and we can prioritize this fix in the following week and deploy it sooner.

**Comment by nicholasgriffinVF** [comment]
Hey, it's Nicholas from my work account, while this is an issue for us, it definitely isn't worth that much to us, especially since you are suggesting that we pay to improve your own software not ours, seems a little out of touch if you ask me.

We would be looking to use this alongside your tile hosting subscription service and as such, the cost is already there for us, we don't think that we should be paying anymore just to get a tiny bug fix like this done, for all of your customers, that should be your undertaking.

**Comment by MartinMikita** [comment]
We have fixed this bug and deployed on our server.
